language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "0.10"

script: "npm run-script test-ci"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"

language: python
 - "2.6"
 - "2.7"

install:
 - "pip install ."
 - "pip install -r requirements.txt"

script:
 - "sh run.sh"
 - "nosetests"
